actions/urls.py
from django.urls import path
from . import views

app_name = 'Actions'

urlpatterns = [
	
]

simple_posts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('simple_posts_accounts.urls', namespace='Accounts')),
    path('', include('simple_posts_posts.urls', namespace='posts')),
    path('', include('actions.urls', namespace='Actions')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simple_posts_accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'Accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/<int:action_id>/<int:user_id>/', views.dashboard, name='dashboard'),
    path('', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('Accounts:password_change_done')), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('users/', views.user_list, name='user_list'),
    path('users/<username>/', views.user_detail, name='user_detail'),
    path('follow/<int:user_id>/', views.follow_user, name='follow_user'),
    path('unfollow/<int:user_id>/', views.unfollow_user, name='unfollow_user'),
]

simple_posts_posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('posts/', views.post_list, name='post_list'),
    path('create/', views.create_post, name='create_post'),
    path('create_comment/<int:post_id>/', views.create_comment, name='create_comment'),
    path('comment_list/<int:post_id>/', views.comment_list, name='comment_list'),
    path('post_detail/<int:year>/<int:month>/<int:day>/<slug:slug>/<int:id>/', views.post_detail, name='post_detail'),
    path('like_post/<int:post_id>/', views.like_post, name='like_post'),
    path('unlike_post/<int:post_id>/', views.unlike_post, name='unlike_post'),
    path('most_liked/', views.most_liked, name='most_liked'),
]

simple_posts_accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class Profile(models.Model):
    OCCUPATION_CHOICES = (
        ('student', 'Student'),
        ('business man', 'Business man'),
        ('trader', 'Trader'),
        ('employee', 'Employee'),
        ('technician', 'Technician'),
    )
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    occupation = models.CharField(
        max_length=25, choices=OCCUPATION_CHOICES, blank=True)
    photo = models.ImageField(upload_to='Users_Photos', blank=True)
    address = models.CharField(max_length=50, blank=True)
    school = models.CharField(max_length=50, blank=True)
    business_name = models.CharField(max_length=50, blank=True)
    business_address = models.CharField(max_length=50, blank=True)
    school_address = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return 'profile for {}'.format(self.user.username)

class Contact(models.Model):
    user_from = models.ForeignKey('auth.User', related_name='rel_from_set', on_delete=models.CASCADE)
    user_to = models.ForeignKey('auth.User', related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return '{} follows {}'.format(self.user_from, self.user_to)

#following = models.ManyToManyField('self', through=Contact, related_name='followers', symmetrical=False)

# Add following field to User dynamically
User.add_to_class('following', models.ManyToManyField('self', through=Contact, related_name='followers', symmetrical=False))

simple_posts_accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from simple_posts_accounts.models import Profile

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords did not match.')
        return cd['password2']

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'occupation', 'business_name', 'school', 'address', 'photo')

simple_posts_accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from simple_posts_accounts.forms import UserRegistrationForm, ProfileEditForm, UserEditForm
from simple_posts_accounts.models import Profile
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from simple_posts_accounts.models import Contact
from django.http import JsonResponse
from common.decorators import ajax_required
from django.views.decorators.http import require_POST
from actions.utils import create_action
from actions.models import Action

@login_required
def user_list(request):
    users = User.objects.filter(is_active=True).exclude(username=request.user.username)
    return render(request, 'user_list.html', {'section': 'people', 'users': users})

@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    return render(request, 'user_detail.html', {'section': 'people', 'user': user})

@login_required
def dashboard(request, action_id = None, user_id = None):
    # Display all actions if user does not follow other users
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list('id', flat=True)
    # Display only actions of people which users follow if they indeed follow other users
    if following_ids:
        actions = actions.filter(user_id__in=following_ids)
    if user_id and action_id:
        actions = actions.exclude(id = action_id)
    actions = actions.select_related('user', 'user__profile').prefetch_related('target')[:10]
    return render(request, 'dashboard.html', {'section': 'dashboard', 'actions': actions})

def register(request):
    if request.method == 'GET':
        user_form = UserRegistrationForm()
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # We don't save immediately
            new_user = user_form.save(commit=False)
            # We instead set the password first with the 'set_password' method for proper encryption.
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            # We have to associate each new user with an empty profile that can be edited later
            Profile.objects.create(user=new_user)
            create_action(new_user, 'created a new account')
            return render(request, 'register_done.html', {'new_user': new_user})
    return render(request, 'register.html', {'user_form': user_form})


@login_required
def edit_profile(request):
    if request.method == 'GET':
        user_edit_form = UserEditForm(instance=request.user)
        profile_edit_form = ProfileEditForm(instance=request.user.profile)
    if request.method == 'POST':
        user_edit_form = UserEditForm(instance=request.user, data=request.POST)
        profile_edit_form = ProfileEditForm(
            instance=request.user.profile, data=request.POST, files=request.FILES)
        if user_edit_form.is_valid() and profile_edit_form.is_valid():
            user_edit_form.save()
            profile_edit_form.save()
            create_action(request.user, 'updated his profile')
            messages.success(request, 'Profile updated successfully')
            return render(request, 'dashboard.html')
        else:
            messages.error(request, 'Failed to update profile')
    return render(request, 'edit_profile.html', {'user_edit_form': user_edit_form, 'profile_edit_form': profile_edit_form})

@login_required
def follow_user(request, user_id):
    user = User.objects.get(id=user_id)
    Contact.objects.get_or_create(user_from=request.user, user_to=user)
    create_action(request.user, 'follows: ', user)
    return redirect(user)

@login_required
def unfollow_user(request, user_id):
    user = User.objects.get(id=user_id)
    Contact.objects.filter(user_from=request.user, user_to=user).delete()
    create_action(request.user, 'unfollowed: ', user)
    return redirect(user)

simple_posts_accounts/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	    <title> {% block title %}  {% endblock title %} </title>
	<link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'mine.css' %}">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
</head>
<body>

    <!-- Script files -->
    <script src="{% static 'jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'bootstrap.bundle.min.js' %}" type="text/javascript"></script> 

{% block content %}  {% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js">
</script>
<script>
var csrftoken = Cookies.get('csrftoken');
  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken);
      }
    }
  });
  $(document).ready(function(){
    {% block javascript %}
    console.log('ready');
    {% endblock %}
  });
</script>

<script>
$(function () {
  width = $(window).width();
  parseInt(width);
  if (width > 768){
  $('[data-toggle="tooltip"]').tooltip()
};
})
</script>

</body>
</html>

simple_posts_accounts/templates/dashboard.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block title %}
    Dashboard
{% endblock title %}

{% block content %}
    {% include 'navbar.html' %}

    {% for removal in removals %}
        {{removal}}
    {% endfor %}

    {% for action in actions %}
        {% include 'actions_detail.html' %}
    {% endfor %}

    {% if messages %}
    	{% for message in messages %}
    		<div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
			  {{message|safe}}
			  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
			    <span aria-hidden="true">&times;</span>
			  </button>
			</div>
    	{% endfor %}
    {% endif %}
    <h2>
        Your Dasshboard <a href="{% url 'Accounts:password_change' %}" class="btn btn-info"> change password </a>
    </h2>
    <a href="{% url 'Accounts:edit_profile' %}" class="btn btn-info"> Edit Profile </a>
{% endblock content %}

simple_posts_accounts/templates/edit_profile.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Edit Profle
{% endblock title %}

{% block content %}
<h2 class="text-center">
    Edit Your Profile
</h2>
    <form action="." method="post" enctype="multipart/form-data">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{user_edit_form.email|as_crispy_field}}
                </div>
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{user_edit_form.first_name|as_crispy_field}}
                </div>
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{user_edit_form.last_name|as_crispy_field}}
                </div>
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{profile_edit_form.school|as_crispy_field}}
                </div>
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{profile_edit_form.date_of_birth|as_crispy_field}}
                </div>
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{profile_edit_form.occupation|as_crispy_field}}
                </div>
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{profile_edit_form.address|as_crispy_field}}
                </div>
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{profile_edit_form.business_name|as_crispy_field}}
                </div>
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-6 text-center">
                    {{profile_edit_form.photo|as_crispy_field|cut:'Users_Photos/'}}
                </div>
            </div>
            <div class="text-center">
                <input type="submit" value="Save changes" class="btn btn-info btn-sm"> <a href="{% url 'Accounts:dashboard' %}" class="btn btn-info btn-sm"> Dashboard </a>
            </div>
        </div>
        {% csrf_token %}
    </form>
{% endblock content %}

simple_posts_accounts/templates/expressNav.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% block content %}
<nav class="navbar navbar-expand-xl navbar-light bg-dark sticky-top p-2">
    <a class="navbar-brand img-fluid" href="#">  <img src="#" alt="EXPRESS" width="30" height="30"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'Accounts:user_list' %}"> People <span class="sr-only">(current)</span></a>
            </li>
        </ul>
       <form>
  <div class="form-row">
    <div class="col">
      {{form.username|as_crispy_field}}
    </div>
    <div class="col">
      {{form.password|as_crispy_field}}
    </div>
    <div class="col">
      <input type="submit" value="Login" class="btn btn-info btn-sm"> 
    </div>
  </div>
</form>
</div>
</nav>
{% endblock content %}

simple_posts_accounts/templates/navbar.html
<!DOCTYPE html>
{% block content %}
<nav class="navbar navbar-expand-md navbar-light bg-dark sticky-top p-1">
    <a class="navbar-brand img-fluid" href="#"> {% if request.user.profile.photo %}
    <img src="{{ request.user.profile.photo.url }}" width="45px" height="45px" class="border rounded-circle">
    {% else %} <i class="fa fa-user"></i> {% endif %} </a>

    <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
                <a class="nav-link" {% if section == 'post_list' %} style="color: #999;" {% endif %}  href="{% url 'posts:post_list' %}" style="color: white;"> Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" {% if section == 'dashboard' %} style="color: #999;" {% endif %}  href="{% url 'Accounts:dashboard' %}" style="color: white;"> Dashboard <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" {% if section == 'people' %} style="color: #999;" {% endif %} style="color: white;" href="{% url 'Accounts:user_list' %}"> Other Users <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" style="color: white;" href="{% url 'posts:create_post' %}"> Post <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" {% if section == 'most_liked' %} style="color: #999;" {% endif %} style="color: white;" href="{% url 'posts:most_liked' %}"> Most Liked <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <span>
        {% if request.user.is_authenticated %}
        <span class="nav-item text-white">
            Welcome {{request.user.first_name|capfirst}} <a href="{% url 'Accounts:logout' %}" class="btn btn-info"> Logout </a>
        </span>
        {% else %}
        <span class="nav-item text-white">
           <a href="{% url 'Accounts:login' %}" class="btn btn-info"> Login </a>
        </span>
        {% endif %}
    </span>
</div>
</nav>
{% endblock content %}

simple_posts_accounts/templates/profile.html
{% block content %}
    {{request.user.username}}
{% endblock %}

simple_posts_accounts/templates/register.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Register
{% endblock title %}

{% block content %}
    <form action="." method="post">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{user_form.username|as_crispy_field}}
                </div>
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{user_form.first_name|as_crispy_field}}
                </div>
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{user_form.last_name|as_crispy_field}}
                </div>
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{user_form.email|as_crispy_field}}
                </div>
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{user_form.password|as_crispy_field}}
                </div>
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{user_form.password2|as_crispy_field}}
                </div>
            </div>
            <div class="text-center">
                <input type="submit" value="Register" class="btn btn-info btn-sm">
            </div>
        </div>
        {% csrf_token %}
    </form>
{% endblock content %}

simple_posts_accounts/templates/register_done.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block title %}
Dasshboard
{% endblock title %}

{% block content %}
    <p>
        Welcome {{new_user.first_name}} <a href="{% url 'Accounts:login' %}" class="btn btn-info btn-sm"> login </a>
    </p>
{% endblock content %}

simple_posts_accounts/templates/user_detail.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block title %}
    {{user.username|capfirst}}
{% endblock title %}

{% block content %}
{% include 'navbar.html' %}
<div class="container-fluid">
	<div class="row mt-1 text-center justify-content-center border border-dark p-1 m-md-3 align-items-center">

		<div class="col-12 col-sm-6 col-md-5 col-lg-4 col-xl-3 text-center">
			  {% if user.profile.photo %}
			    <img src="{{user.profile.photo.url}}" alt="{{user.username}}'s image" class="img-fluid">
			  {% endif %}
		</div>

		<div class="col-12 col-sm-6 col-lg-4">
			  <h4>{{ user.get_full_name|capfirst }}</h4>

			  <h4>
			  	Total Posts: {{user.posts.count}}
			  </h4>

			  <h4>
			  	Occupation: {{user.profile.occupation|capfirst}}
			  </h4>

			   <h4>
			  	Birth Day: {{user.profile.date_of_birth}}
			  </h4>

			   <h4>
			  	Address: {{user.profile.address}}
			  </h4>

			   <h4>
			  	Attends: {{user.profile.school}}
			  </h4>

			{% with total_followers=user.followers.count %}
			   <button type="button" class="btn btn-primary" type="button" data-toggle="modal" data-target="#exampleModalCenter">
  					<span class="badge badge-light">{{ total_followers }}</span>
  					follower{{ total_followers|pluralize }} 
				</button>
			{% endwith %}

			    <a href="{% if request.user not in user.followers.all %}{% url 'Accounts:follow_user' user.id %}{% else %}{% url 'Accounts:unfollow_user' user.id %}{% endif %}" class="btn btn-info">
			      {% if request.user not in user.followers.all %}
			        Follow
			      {% else %}
			        Unfollow
			      {% endif %}
			    </a>

			 {% with people_followed=user.following.count %}
			    <button type="button" class="btn btn-primary" data-toggle="modal" type="button" data-target="#modal4followers">
  					following <span class="badge badge-light">{{ people_followed }}</span> 
				</button>
			{% endwith %}
		</div>
	</div>
	<div id="image-list" class="p-0">
		{% include "post_list_ajax.html" with posts=user.posts.all %}
	</div>
 </div>


<!-- Modal -->
<div class="modal fade" id="modal4followers" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle"> Following </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% for user in user.following.all %}
        <div class="media">
        	{% if user.profile.photo %}
			  <img class="align-self-center mr-3 rounded-circle" src="{{user.profile.photo.url}}" width="40px" height="40px" alt="Generic placeholder image">
			  {% else %}
			  <img class="align-self-center mr-3 rounded-circle" src="{% static 'best-government.jpg' %}" width="40px" height="40px" alt="Generic placeholder image">
			  {% endif %}
			  <div class="media-body text-center">
			    <h5 class="mt-0">{{user.username}}</h5>
			    <p> Lorem ipsum dolor sit proident, sicia desit anim id est laborum. </p>
			    <hr>
			  </div>
		</div>
		{% endfor %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger mx-auto" data-dismiss="modal">close</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle"> Followers </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       	{% for user in user.followers.all %}
		<div class="media">
        	{% if user.profile.photo %}
			  <img class="align-self-center mr-3 rounded-circle" src="{{user.profile.photo.url}}" width="40px" height="40px" alt="Generic placeholder image">
			  {% else %}
			  <img class="align-self-center mr-3 rounded-circle" src="{% static 'best-government.jpg' %}" width="40px" height="40px" alt="Generic placeholder image">
			  {% endif %}
			  <div class="media-body text-center">
			    <h5 class="mt-0">{{user.username}}</h5>
			    <p> Lorem ipsum dolor sit proident, sicia desit anim id est laborum. </p>
			    <hr>
			  </div>
		</div>
		{% endfor %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger mx-auto" data-dismiss="modal">close</button>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

simple_posts_accounts/templates/user_list.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title> Other users </title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'mine.css' %}">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
</head>
<body class="bg-dark">

<!-- Script files -->
    <script src="{% static 'jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'bootstrap.bundle.min.js' %}" type="text/javascript"></script> 


{% include 'navbar.html' %}
<div class="container-fluid">
    <div class="row justify-content-center">
        {% for user in users %}
        <div class="col-12 col-sm-auto col-md-auto col-lg-auto col-xl-auto my-1">
            {% if user.profile.photo %}
            <a href="{{user.get_absolute_url}}">
                    <img src="{{user.profile.photo.url}}" alt="{{user.username|capfirst}}'s image" class=" user-image">
            </a>
                {% else %}
            <a href="{{user.get_absolute_url}}">
                    <img src="{% static 'best-government.jpg' %}" alt="{{user.username|capfirst}}'s image" class="user-image">
            </a>
            {% endif %}
            <figcaption class="text-center" style="color: white;"> {{ user.get_full_name|capfirst }} </figcaption>
        </div>
        {% endfor %}
    </div>
</div>
</body>
</html>