actions/urls.py
from django.urls import path
from . import views

app_name = 'Actions'

urlpatterns = [
	
]

simple_posts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('simple_posts_accounts.urls', namespace='Accounts')),
    path('', include('simple_posts_posts.urls', namespace='posts')),
    path('', include('actions.urls', namespace='Actions')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simple_posts_posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('posts/', views.post_list, name='post_list'),
    path('create/', views.create_post, name='create_post'),
    path('create_comment/<int:post_id>/', views.create_comment, name='create_comment'),
    path('comment_list/<int:post_id>/', views.comment_list, name='comment_list'),
    path('post_detail/<int:year>/<int:month>/<int:day>/<slug:slug>/<int:id>/', views.post_detail, name='post_detail'),
    path('like_post/<int:post_id>/', views.like_post, name='like_post'),
    path('unlike_post/<int:post_id>/', views.unlike_post, name='unlike_post'),
    path('most_liked/', views.most_liked, name='most_liked'),
]

simple_posts_posts/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts')
    date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)
    image = models.ImageField(upload_to='Images')
    title = models.CharField(max_length=100)
    body = models.TextField(blank=True)
    slug = models.SlugField(max_length=100)
    likes = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='liked', blank=True)
    total_likes = models.PositiveIntegerField(db_index=True, default=0)#for purposes of denormalisation.

    class Meta:
        ordering = ('-total_likes', 'date')

    def __str__(self):
        return self.title

    # Use this method to automatically set the slug of the image.
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:post_detail', args=[self.date.year, self.date.month, self.date.day, self.slug, self.id])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comment', blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    body = models.TextField()
    status = models.BooleanField(default=True)

    def __str__(self):
        return '{} commented on {}'.format(self.writer, self.post)

simple_posts_posts/forms.py
from django import forms
from simple_posts_posts.models import Post, Comment


class PostCreationForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('image', 'title', 'body',)

class CommentCreationForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('body',)

simple_posts_posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from simple_posts_posts.models import Post, Comment
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from simple_posts_posts.forms import PostCreationForm, CommentCreationForm
from django.utils import timezone 
from django.http import JsonResponse
from simple_posts_posts.utility import Utility
from common.decorators import ajax_required
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from actions.utils import create_action
from django.conf import settings

def post_list(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, 8)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        posts = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request, 'post_list_ajax.html', {'posts': posts, 'section': 'post_list'})
    return render(request, 'post_list.html', {'posts': posts, 'section': 'post_list'})

@login_required
def post_detail(request, year, month, day, slug, id=None):
    post = get_object_or_404(Post, date__year=year, date__month=month, date__day=day, slug=slug, id=id)
    return render(request, 'post_detail.html', {'post': post, 'section': 'post_detail'})

@login_required
def create_post(request):
    if request.method == 'GET':
        form = PostCreationForm()
    if request.method == 'POST':
        form = PostCreationForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            create_action(request.user, 'created a new post', new_post)
            messages.success(
                request, "Your post '{}'. was uploaded successfully".format(cd['title']))
            return redirect('posts:post_list')
    return render(request, 'create_post.html', {'form': form, 'section': 'make post'})


def create_comment(request, post_id):
    if request.method == 'GET':
        form = CommentCreationForm()
    if request.method == 'POST':
        post = Post.objects.get(id=post_id)
        form = CommentCreationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.writer = request.user
            new_comment.save()
            create_action(request.user, 'added a comment to: ', new_comment.post)
            messages.success(request, "You added a comment to {}'s post: '{}'.".format(post.author, post.title.title()))
            return redirect('posts:post_list')
    return render(request, 'create_comment.html', {'form': form})

@login_required
def like_post(request, post_id):
    post = Post.objects.get(id=post_id)
    post.likes.add(request.user)
    messages.success(request, "You liked {}'s post: '{}'.".format(post.author, post.title.title()))
    return redirect('posts:post_list')

@login_required
def unlike_post(request, post_id):
    post = Post.objects.get(id=post_id)
    post.likes.remove(request.user)
    messages.success(request, "You unliked {}'s post: '{}'.".format(post.author, post.title.title()))
    return redirect('posts:post_list')

@login_required
def comment_list(request, post_id):
    post = Post.objects.get(id = post_id)
    return render(request, 'comment_list.html', {'post': post})

@login_required
def most_liked(request):
    posts = Post.objects.all().order_by('-total_likes', 'date')[0:4]
    return render(request, 'most_liked.html', {'posts': posts, 'section': 'most_liked'})

simple_posts_posts/templates/comment_list.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    comment list
{% endblock title %}

{% block content %}
    {% for comment in post.comments.all %}
       {{forloop.counter}}) {{comment.body}} By: {{comment.writer|capfirst}} <img src="{{comment.writer.profile.photo.url}}" width="20" height="20"><br>
    {% endfor %}
{% endblock content %}

simple_posts_posts/templates/create_comment.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Create Comment
{% endblock title %}

{% block content %}
<div class="container-fluid">
    <h4 class="text-center">
        Create New Comment
    </h4>
    <form action="." method="post">
        <div class="row justify-content-center">
        <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4">
            {{form.body|as_crispy_field}}
        </div>
    </div>
    <div class="text-center">
        <button type="submit" class="btn btn-success btn-sm"> submit </button>
    </div>
        {% csrf_token %}
    </form>
</div>
{% endblock content %}

simple_posts_posts/templates/create_post.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}
    Create Post
{% endblock title %}

{% block content %}
{% include 'navbar.html' %}
    <h3>
        Create New Post
    </h3>
    <form action="." method="post" enctype="multipart/form-data">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{form.title|as_crispy_field}}
                </div>
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{form.image|as_crispy_field}}
                </div>
                <div class="col-11 col-sm-6 col-md-5 col-lg-4 col-xl-3">
                    {{form.body|as_crispy_field}}
                </div>
            </div>
        </div>
        <div class="text-center">
            <button class="btn btn-sm btn-info text-center" type="submit">submit</button>
        </div>
        {% csrf_token %}
    </form>
{% endblock content %}

simple_posts_posts/templates/most_liked.html
{% extends "base.html" %}
{% block title %} most liked posts {% endblock %}
{% load static %}

{% block content %}
{% include 'navbar.html' %}
  <div class="jumbotron jumbotron-fluid p-2 mb-0">
  <div class="container">
    <h1 class="text-center">Most Liked Posts</h1>
    <p class="lead text-center">This is a list of posts with the most number of likes. It is determined by the number of likes that the post has.</p>
  </div>
</div>
        <div class="d-flex flex-row mb-3 flex-wrap flex-fill justify-content-center flex-wrap bg-black">
        {% for post in posts %}
        {% with post_likes=post.likes.all %}
            <div class="card border border-dark m-1 pb-2 width">
                <div class="text-center p-1 bg-black" style="font-size: 1.75rem; color: white;">
                    {{post.title|capfirst|truncatewords:'3'}}
                </div>
                <img src="{{post.image.url}}" alt="{{post.title}}'s image" height="290px"> 
                <div class="card-body text-justify">
                    {% if post.body|length > 20 %}
                    <p class="card-text">{{post.body|truncatewords:'20'}}</p>
        
                    <div class="text-center">
                        <a style="color: black; text-decoration: none;" class="mr-3" data-toggle="tooltip" data-placement="top" title="{{post.likes.count}} likes" href="{% if request.user in post_likes %} {% url 'posts:unlike_post' post.id %} {% else %} {% url 'posts:like_post' post.id %} {% endif %}" > 
                            {% if request.user in post_likes %} 
                            <img src="{% static 'thumbs-down.svg' %}" width="20px" height="20px"> 
                            {% else %} 
                            <img src="{% static 'thumbs-up.svg' %}" width="20px" height="20px">
                            {% endif %} 
                            {{post.likes.count}}
                        </a>
                        <a href="{{post.get_absolute_url}}" data-toggle="tooltip" data-placement="top" title="read post" class="mr-3" style="color: black; text-decoration: none;"> <img src="{% static 'folder-open.svg' %}" width="20px" height="20px"> </a>
                        <a href="{% url 'posts:create_comment' post.id %}" data-toggle="tooltip" data-placement="top" title="comment on post" class="mr-3" style="color: black; text-decoration: none;"> <img src="{% static 'comment.svg' %}" width="20px" height="20px">  </a>
                    {% endif %}    
                    {% if post.comments.all|length > 0 %}
                    <a href="{% url 'posts:comment_list' post.id %}" data-toggle="tooltip" data-placement="top" title="comments: {{post.comments.count}}" class="" style="color: black; text-decoration: none;"> <img src="{% static 'comments.svg' %}" width="20px" height="20px"> </a>
                    {{post.comments.count}}
                    {% endif %}
                </div>
            </div>
        </div>
        {% endwith %}
        {% endfor %}

{% endblock %}

simple_posts_posts/templates/post_detail.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block title %}
    Dashboard
{% endblock title %}

{% block content %}
	<p>
    	{{post.body}}
	</p>
{% endblock content %}

simple_posts_posts/templates/post_list.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load post_tags %}
{% load static %}
{% block title %}
    Posts
{% endblock title %}

{% block content %}
{% include 'navbar.html' %}
<div class="">
{% include 'post_list_ajax.html' %}
<div id="post_list"> </div>
</div>
{% endblock %}

{% block javascript %}    
         $(function(){

      var empty_page = false;
      var page = 1;
      var block_request = false;

      $(window).scroll(function(){
      var margin = $(document).height() - $(window).height() - 200;
      if ($(window).scrollTop() > margin && empty_page == false && block_request == false){
      block_request = true;
      page = page + 1;
      $.get('?page=' + page, function(data){
      if(data == ''){
      empty_page==true;
    }else{
    block_request = false;
    $('#post_list').append(data);
  }
    });
    }
    });
        });
{% endblock javascript %}

simple_posts_posts/templates/post_list_ajax.html
        {% load static %}
        <div class="d-flex flex-row mb-3 flex-wrap flex-fill justify-content-center flex-wrap bg-black">
        {% for post in posts %}
        {% with post_likes=post.likes.all %}
            <div class="card border border-dark m-1 pb-2">
                <div class="text-center p-1 bg-black" style="font-size: 1.75rem; color: white;">
                    {{post.title|capfirst|truncatewords:'3'}}
                </div>
                <img src="{{post.image.url}}" alt="{{post.title}}'s image" height="290px"> 
                <div class="card-body p-0 text-justify">
                    {% if post.body|length > 20 %}
                    <p class="card-text">{{post.body|truncatewords:'20'}}</p>
        
                    <div class="text-center">
                        <a style="color: black; text-decoration: none;" class="mr-3" href="{% if request.user in post_likes %} {% url 'posts:unlike_post' post.id %} {% else %} {% url 'posts:like_post' post.id %} {% endif %}" > 
                            {% if request.user in post_likes %} 
                            <img src="{% static 'thumbs-down.svg' %}" width="20px" height="20px"> 
                            {% else %} 
                            <img src="{% static 'thumbs-up.svg' %}" width="20px" height="20px">
                            {% endif %} 
                            {{post.likes.count}}
                        </a>
                        <a href="{{post.get_absolute_url}}" class="mr-3" style="color: black; text-decoration: none;"> <img src="{% static 'folder-open.svg' %}" width="20px" height="20px"> </a>
                        <a href="{% url 'posts:create_comment' post.id %}" class="mr-3" style="color: black; text-decoration: none;"> <img src="{% static 'comment.svg' %}" width="20px" height="20px">  </a>
                    {% endif %}    
                    {% if post.comments.all|length > 0 %}
                    <a href="{% url 'posts:comment_list' post.id %}" class="" style="color: black; text-decoration: none;"> <img src="{% static 'comments.svg' %}" width="20px" height="20px"> </a>
                    {{post.comments.count}}
                    {% endif %}
                </div>
            </div>
        </div>
        {% endwith %}
        {% endfor %}